# Generated by Django 2.2.19 on 2023-10-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
