# Generated by Django 2.2.19 on 2023-10-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_price',
        ),
    ]
