# Generated by Django 2.2.19 on 2023-09-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_saleitem_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='post',
        ),
    ]
